# =====================================================================
# SECRETS.TOML - CONFIGURACIÓN SEGURA PARA STREAMLIT CLOUD
# =====================================================================

# 1. CLAVE API PARA EL MOTOR DE IA (Deepseek)
# Esta clave ya estaba configurada.
DEEPSEEK_API_KEY = "sk-1be6c6ccda664d8a902bd69376ee3bfc"

# 2. DATOS DE USUARIO PARA EL LOGIN (Contenido privado)
# El contenido completo del CSV se guarda aquí como un string multilínea
[user_data]
csv_content = """
username,password,role,area,approved,celular,correo_personal,correo_institucional,nombre
admin@veracruz.gob.mx,admin123,admin,Todas,True,22223333,admin@gmail.com,admin@veracruz.gob.mx,Sergio Cortina
policiampal@veracruzmunicipio.gob.mx,Poli123,enlace,COMANDANCIA DE LA POLÍCIA MUNICIPAL,True,nan,,,Grecia
dlopez@veracruzmunicipio.gob.mx,Admon123,enlace,ADMINISTRACIÓN,True,nan,,,Daniela Ozuri López Yañez
diralumbrado@veracruzmunicipio.gob.mx,Alum123,enlace,ALUMBRADO PÚBLICO,True,nan,,,Andrea Mantilla
siaveracruz2022@gmail.com,Arch123,enlace,ARCHIVO MUNICIPAL,True,nan,,,Juan Carlos Lara Prado
asuntoslegales@veracruzmunicipio.gob.mx,Legal123,enlace,ASUNTOS LEGALES,True,nan,,,Eduardo Capitaine Manterola
hola@veracruzmunicipio.gob.mx,Aten123,enlace,ATENCIÓN CIUDADANA,True,nan,,,Monserat Schleske
acisneros@veracruzmunicipio.gob.mx,Comer123,enlace,COMERCIO,True,2291502953,,acisneros@veracruzmunicipio.gob.mx,Alan Mauricio Cisneros
erivera@veracruzmunicipio.gob.mx,Turis123,enlace,TURISMO,True,nan,,,Esteban Rivera
rcruz@veracruzmunicipio.gob.mx,Social123,enlace,INSTITUTO MUNICIPAL DE ASISTENCIA SOCIAL,True,nan,,,Rosario Calderón Vargas
proteccionninasyninos@veracruzmunicipio.gob.mx,Sipinna123,enlace,"SISTEMA DE PROTECCIÓN INTEGRAL DE NIÑAS, NIÑOS Y ADOLESCENTES (SIPINNA).",True,nan,,,Rosy Sosa Guizar
mhernandez@veracruzmunicipio.gob.mx,Procu123,enlace,PROCURADURÍA DE LA DEFENSA DE LOS USUARIOS DEL AGUA  (PRODEAGUA),True,nan,,,Misael Hernández Vázquez
secretaria@veracruzmunicipio.gob.mx,pass123,enlace,SECRETARIA,True,nan,,,Cesar Cotera
rruiz@veracruzmunicipio.gob.mx,Teso123,enlace,TESORERÍA MUNICIPAL,True,nan,,,Rosario Ruiz Lagunes
transparencia@veracruzmunicipio.gob.mx,Unidad123,enlace,UNIDAD DE TRANSPARENCIA,True,nan,,,Virginia Utrera
contabilidad@veracruzmunicipio.gob.mx,Conta123,enlace,TESORERÍA MUNICIPAL -CONTABILIDAD GUBERNAMENTAL,True,nan,,,Mario Alfredo Argüelles Juárez
gcrbb53@gmail.com,Egre123,enlace,EGRESOS,True,nan,,,Gustavo Carmona
coordinacion.ingresos@veracruzmunicipio.gob.mx,Ingre123,enlace,TESORERÍA MUNICIPAL - INGRESOS,True,nan,,,Coordinación de Ingresos
subplaneacioncatastral@veracruzmunicipio.gob.mx,Catas123,enlace,SUBDIRECCIÓN DE PLANEACIÓN CATASTRAL,True,nan,,,Subdirección de Planeación Catastral
"""
